// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddExampleSentenceInput struct {
	SentencePl string `json:"sentencePl"`
	SentenceEn string `json:"sentenceEn"`
}

type AddPolishWordInput struct {
	Word         string                 `json:"word"`
	Translations []*AddTranslationInput `json:"translations"`
}

type AddTranslationInput struct {
	EnglishWord      string                     `json:"englishWord"`
	ExampleSentences []*AddExampleSentenceInput `json:"exampleSentences"`
}

type EditExampleSentenceInput struct {
	SentencePl *string `json:"sentencePl,omitempty"`
	SentenceEn *string `json:"sentenceEn,omitempty"`
}

type EditPolishWordInput struct {
	Word         *string                 `json:"word,omitempty"`
	Translations []*EditTranslationInput `json:"translations,omitempty"`
}

type EditTranslationInput struct {
	EnglishWord      *string                     `json:"englishWord,omitempty"`
	ExampleSentences []*EditExampleSentenceInput `json:"exampleSentences,omitempty"`
}

type ExampleSentence struct {
	ID          string       `json:"id"`
	Translation *Translation `json:"translation"`
	SentencePl  string       `json:"sentencePl"`
	SentenceEn  string       `json:"sentenceEn"`
}

type Mutation struct {
}

type PolishWord struct {
	ID           string         `json:"id"`
	Word         string         `json:"word"`
	Translations []*Translation `json:"translations"`
}

type Query struct {
}

type Translation struct {
	ID               string             `json:"id"`
	EnglishWord      string             `json:"englishWord"`
	PolishWord       *PolishWord        `json:"polishWord"`
	ExampleSentences []*ExampleSentence `json:"exampleSentences"`
}
